### ISSUE TITLE
is it possible to post a form on a backend page?

### ISSUE THREAD

**Issue by janky** [bayareawebpro/wp-lumen-plugin-framework#2]
Hi, I'm developing a form in a view displayed in wordpress admin area.

If I post to my controller function how can I return a view with the wordpress admin page template? I'm asking this because if I do a "normal” return $this->helper->view(), my browser display a page with my content but without the admin area template.

Thanks

**Comment by bayareawebpro** [comment]
Instead of posting to a route.  You should post to the same admin panel url.  Here's a helper method I wrote that will generate an admin action url with get params.  It will keep your same panel page and merge an array with the get params.

```
/**
     * Get an Action Url for the Current Admin Page (add to WpHelper)
     * @param $params array
     * @return string
     */
    public function adminAction(array $params = array()){
        $page = app()->make('request')->get('page'); //Wp Admin Page
        $query = http_build_query(array_merge($params, compact('page')));
        $url = admin_url("admin.php?$query");
        return $url;
    }
```

In your controller assign an action url to your view:
```
$action = $this->wpHelper->adminAction(compact('action', 'var1'));
//Result: http://wplumen.local/wp-admin/admin.php?page=my_page&action=test&var1=test
```

In your view:
```
<form method="post" action="{{ $action }}">
        <button 
                type="submit" 
                onclick="return confirm('Are you sure?')"
                class="button button-secondary button-small">
            Submit
        </button>
    </form>
```


Then in your controller before the view is returned:  
```
if(
$request->isMethod('post') && 
$request->get('action') === 'my_action'
){
//Do my action.
}
```

Here's another helper for returning a redirect response within the admin panel controller:
```
    /**
     * Create a new controller instance.
     * @param $url string
     * @return void
     */
    protected function redirect($url){
        with(new RedirectResponse($url))->send(); //Or sendContent() if there's a headers error.
        exit;
    }
```
